"""add activities memories and doctor notes

Revision ID: ae81fbac8651
Revises: 0afcf58f723e
Create Date: 2026-07-13 10:09:41.555831
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ae81fbac8651"
down_revision: Union[str, Sequence[str], None] = "0afcf58f723e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("media_reference", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_definitions_patient_id"),
        "activity_definitions",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "doctor_notes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("doctor_user_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_shared_with_caregiver", sa.Boolean(), nullable=False),
        sa.Column("follow_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_doctor_notes_doctor_user_id"), "doctor_notes", ["doctor_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_doctor_notes_patient_id"), "doctor_notes", ["patient_id"], unique=False
    )
    op.create_table(
        "memory_categories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_categories_patient_id"), "memory_categories", ["patient_id"], unique=False
    )
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("activity_id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("completion_source", sa.String(length=40), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("device_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activity_definitions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_logs_activity_id"), "activity_logs", ["activity_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_logs_patient_id"), "activity_logs", ["patient_id"], unique=False
    )
    op.create_table(
        "memory_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("media_type", sa.String(length=20), nullable=False),
        sa.Column("object_key_or_url", sa.String(length=1000), nullable=True),
        sa.Column("capture_date", sa.Date(), nullable=True),
        sa.Column("people_labels_json", sa.JSON(), nullable=False),
        sa.Column("spoken_prompt", sa.Text(), nullable=True),
        sa.Column("visibility", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["memory_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_items_category_id"), "memory_items", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_items_patient_id"), "memory_items", ["patient_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memory_items_patient_id"), table_name="memory_items")
    op.drop_index(op.f("ix_memory_items_category_id"), table_name="memory_items")
    op.drop_table("memory_items")
    op.drop_index(op.f("ix_activity_logs_patient_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_activity_id"), table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_index(op.f("ix_memory_categories_patient_id"), table_name="memory_categories")
    op.drop_table("memory_categories")
    op.drop_index(op.f("ix_doctor_notes_patient_id"), table_name="doctor_notes")
    op.drop_index(op.f("ix_doctor_notes_doctor_user_id"), table_name="doctor_notes")
    op.drop_table("doctor_notes")
    op.drop_index(op.f("ix_activity_definitions_patient_id"), table_name="activity_definitions")
    op.drop_table("activity_definitions")
    # ### end Alembic commands ###
